### PR TITLE
you merged b4 i fixed what you asked, this is after requrements.txt is back to place

### PR DESCRIPTION
**Pull request by devshaki**
# Pull Request Template

## Description

Please briefly describe the purpose of this pull request.

## Changes Made

List the main changes and improvements introduced by this PR.

- Change 1
- Change 2
- ...

## Screenshots (if applicable)

If your changes include visual modifications, please attach relevant screenshots here.

## Checklist

Please make sure that your pull request meets these requirements before submission:

- [ ] The code follows the project's coding standards and style guidelines.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation (if applicable) has been updated to reflect the changes.
- [ ] The code has been reviewed and any issues have been addressed.
- [ ] The PR title is descriptive and follows the project's naming conventions.

## Related Issues

Link any related issues here using the format `Fixes #123` or `Closes #456`.

## Checks

Before merging, the following checks should pass:

- [ ] Code review has been completed.
- [ ] All tests pass successfully.
- [ ] Documentation (if applicable) has been reviewed and updated.
- [ ] The PR has at least one approval from a maintainer or reviewer.
- [ ] Any relevant issues have been linked and addressed.
- [ ] I checked for issues arising after run

### CODE REVIEW

**Comment by prasad-chavan1** [comment]
No worries Close this pull request I agreed with ur 1st commit

**Comment by devshaki** [comment]
alr <3 thank you

**Comment by prasad-chavan1** [comment]
> alr <3 thank you

Open new issues and contribute

**Comment by devshaki** [comment]
what do you mean, add an issues with this commit?

**Comment by prasad-chavan1** [comment]
> what do you mean, add an issues with this commit?

No go to issues section and try to contribute or open new issues if you want any type of changes or blaablaaaa.....

**Comment by devshaki** [comment]
oh alr!

**Comment by prasad-chavan1** [comment]
> oh alr!

Yeahhh Buddy ❤️

**Pull request closed without merging**
