### PR TITLE
changed save icon to red

### PR DESCRIPTION
**Pull request by Akhilbisht798**
#2 

Made the changes needed for the website.
Screenshot from 2023-10-02 09-52-42

### CODE REVIEW

**Comment by prasad-chavan1** [comment]
@Akhilbisht798  Great Job

**Comment by prasad-chavan1** [comment]
> #2
> 
> Made the changes needed for the website. Screenshot from 2023-10-02 09-52-42

You have done great job
Once again go through whole site & check for all features and colors combination then ill merge and close this issue 😄

**Comment by prasad-chavan1** [comment]
@Akhilbisht798  https://www.linkedin.com/in/prasad-chavan2003/  connect lets do some discusson

**Comment by Akhilbisht798** [comment]
Yes i have checked entire code and it look good to me.

**Comment by Akhilbisht798** [comment]
@prasad-chavan1 surely. I will connect to you.

**Comment by prasad-chavan1** [comment]
> Yes i have checked entire code and it look good to me.

When i refresh page then the icon color is reverting back to green solve that bug

**Comment by Akhilbisht798** [comment]
Hey this might be due to cache can you check in some other browser can confirm it. I have same problem but i have tried it a another browser and it work good.

**Comment by Akhilbisht798** [comment]
If that is not the case  with you i can look what is the problem.

**Comment by prasad-chavan1** [comment]
> If that is not the case with you i can look what is the problem.

Come on linkedIn chats

**Comment by prasad-chavan1** [comment]
okay I'll try it later today

**Comment by Akhilbisht798** [comment]
Hey I have fixed the issue. This is complete.

**Comment by prasad-chavan1** [comment]
> Hey I have fixed the issue. This is complete.

Try changing logo that stuff also comes under color combination & themes

**Comment by Akhilbisht798** [comment]
Hey @prasad-chavan1, I can open another pr for that. It may took some time.
And It will be more clear and concise that i do that stuff seprately in order to not clear any conflict

**Comment by Akhilbisht798** [comment]
Also we will some discussion. To that stuff. I have'nt started searching for logo yet. But i may start this process using ai genration

**Pull request merged**
