### PR TITLE
Added functionality to the edit profile button in profile page

### LINKED ISSUE #1: Add Function for Edit Profile Btn
**Coders, there is a edit profile button on profile page**
Add functionality to that button in views.py file and also include specific URL pattern for that btn

### PR DESCRIPTION
**Pull request by Tanay-ErrorCode**
## Description

I added functionality to *edit profle* button in the profile section.

## Changes Made

- Edited profile.html to add link for edit
- created edit.html to add the page
- created editprofile.js to rename the display name of input(images)
- edited views.py to add functionality to update the user data
- edited urls.py to add the link for editing profile

## Screenshots
The edit profile page:
Screenshot from 2023-10-02 09-05-09

The profile page:
Screenshot from 2023-10-02 09-05-16

If your changes include visual modifications, please attach relevant screenshots here.

## Checklist

Please make sure that your pull request meets these requirements before submission:

- [ ] The code follows the project's coding standards and style guidelines.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation (if applicable) has been updated to reflect the changes.
- [ ] The code has been reviewed and any issues have been addressed.
- [ ] The PR title is descriptive and follows the project's naming conventions.

## Related Issues

Closes #1 issue.

## Checks

Before merging, the following checks should pass:

- [ ] Code review has been completed.
- [ ] All tests pass successfully.
- [ ] Documentation (if applicable) has been reviewed and updated.
- [ ] Any relevant issues have been linked and addressed.
- [ ] The PR has at least one approval from a maintainer or reviewer.
- [ ] I checked for issues arising after run

### CODE REVIEW

**Review by prasad-chavan1 — CHANGES_REQUESTED** [review]
what about login_required ???in views.py and dont go for making seperate page of edit profile Just set popup on profile page itself

**Comment by Tanay-ErrorCode** [comment]
@prasad-chavan1 I have completed these all tasks mentioned in [this comment](https://github.com/prasad-chavan1/Animesthetic-Social-Media/issues/1#issuecomment-1741995429), if you want any further changes, please create a new issue.

**Comment by prasad-chavan1** [comment]
> @prasad-chavan1 I have completed these all tasks mentioned in [this comment](https://github.com/prasad-chavan1/Animesthetic-Social-Media/issues/1#issuecomment-1741995429), if you want any further changes, please create a new issue.

You didnt completed as per my requirements i didnt said to build up seperate page for that 🛑 i want popup like that create post element......

**Comment by Tanay-ErrorCode** [comment]
@prasad-chavan1 You never mentioned your requirements. The issue was only to add functionality to edit profile and it is working well and good.

**Comment by Tanay-ErrorCode** [comment]
> Okay m updating my issue template but i cant go with seperate page i just wanna show popup.

How can you update the issue when the changes are done and PR is there ?

**Comment by prasad-chavan1** [comment]
Go as per i said build popup not separate page

**Comment by Tanay-ErrorCode** [comment]
> Okay m updating my issue template but i cant go with seperate page i just wanna show popup

How can you change the issue when changes are done and PR is raised ? 
First of all you should have a specific design or blueprint for this website, so that you can decide before creating an issue.

**Comment by prasad-chavan1** [comment]
Ok, ill do that start working on my suggestions build a popup

**Comment by Tanay-ErrorCode** [comment]
> Go as per i said build popup not separate page

When you said? After I completed the PR? This is not fair.

**Comment by prasad-chavan1** [comment]
> > Go as per i said build popup not separate page
> 
> When you said? After I completed the PR? This is not fair.

Sorry for that now go as per i said

**Comment by prasad-chavan1** [comment]
> > Go as per i said build popup not separate page
> 
> When you said? After I completed the PR? This is not fair.

Have yuh fixed >??

**Comment by Tanay-ErrorCode** [comment]
> > > Go as per i said build popup not separate page
> > 
> > 
> > When you said? After I completed the PR? This is not fair.
> 
> Have yuh fixed >??

Yes, I will do it.

**Comment by Tanay-ErrorCode** [comment]
@prasad-chavan1 If you are going to make this website responsive, then the content on the popup may misbehave.

**Comment by prasad-chavan1** [comment]
> @prasad-chavan1 Should I use **Cropper.js** library for cropping and adjusting profile image?

Yeahh surely

**Pull request closed without merging**
